import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import allRideRentalImage from "../assets/AllRideRental.jpg";
// import investmentIcon from "../assets/investment-icon.png";
// import listingIcon from "../assets/listing-icon.png";
// import earningChart from "../assets/earning-chart.png";
// import partnerApp from "../assets/partner-app.png";

const PartnerPage = () => {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState("invest"); // 'invest' or 'list'
  const [formData, setFormData] = useState({
    name: "",
    phone: "",
    email: "",
    city: "",
    partnershipType: "invest",
    investmentAmount: "",
    vehicleType: "",
    vehicleCount: "1",
    existingVehicle: false,
    message: ""
  });

  useEffect(() => {
    window.scrollTo({
      top: 0,
      behavior: 'smooth'
    });
  }, []);

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData({
      ...formData,
      [name]: type === 'checkbox' ? checked : value
    });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    // Here you would typically submit to your backend API
    console.log("Partner form submitted:", formData);
    alert("Thank you for your interest! Our team will contact you within 24 hours.");
    setFormData({
      name: "",
      phone: "",
      email: "",
      city: "",
      partnershipType: "invest",
      investmentAmount: "",
      vehicleType: "",
      vehicleCount: "1",
      existingVehicle: false,
      message: ""
    });
  };

  // Partnership models
  const partnershipModels = [
    {
      id: "invest",
      title: "Invest in Our Fleet",
      subtitle: "Buy new vehicles through us and earn 70% revenue share",
      icon: "💰",
      color: "from-green-500 to-emerald-600",
      features: [
        "Invest in new bikes/cars through All Ride Rental",
        "70:30 revenue share (70% for you, 30% for us)",
        "Monthly payments to your bank account",
        "3-year partnership agreement",
        "Vehicle ownership transferred to you after 3 years",
        "Full maintenance and insurance coverage by us",
        "Access to Partner App for tracking earnings",
        "Expert guidance on high-demand vehicle models"
      ],
      howItWorks: [
        {
          step: "1",
          title: "Choose Investment",
          description: "Select vehicle type and investment amount based on market demand"
        },
        {
          step: "2",
          title: "Sign Agreement",
          description: "3-year partnership agreement with clear terms"
        },
        {
          step: "3",
          title: "Vehicle Purchase",
          description: "We handle purchase, registration, and onboarding"
        },
        {
          step: "4",
          title: "Start Earning",
          description: "Receive 70% of revenue monthly to your bank account"
        }
      ],
      faqs: [
        {
          question: "What am I investing in?",
          answer: "You'll be investing in buying new bikes or cars which will be rented out through All Ride Rental platform."
        },
        {
          question: "How much will I earn?",
          answer: "You receive 70% of the revenue generated by your vehicle. With our demand-based placement, expect excellent returns."
        },
        {
          question: "How will I get paid?",
          answer: "We credit your earnings every month directly to your bank account."
        },
        {
          question: "What happens after 3 years?",
          answer: "The vehicle ownership is transferred to you. You can use it personally, resell it, or continue the partnership."
        }
      ]
    },
    {
      id: "list",
      title: "List Your Vehicle",
      subtitle: "List your existing vehicle and earn 70% revenue share",
      icon: "🚗",
      color: "from-blue-500 to-cyan-600",
      features: [
        "List your existing bike/car with us",
        "70:30 revenue share (70% for you, 30% for us)",
        "Monthly payments to your bank account",
        "Flexible partnership terms",
        "Keep vehicle ownership",
        "We handle maintenance and insurance",
        "Real-time booking management",
        "Vehicle tracking and security"
      ],
      howItWorks: [
        {
          step: "1",
          title: "Vehicle Inspection",
          description: "Our team inspects and approves your vehicle"
        },
        {
          step: "2",
          title: "Documentation",
          description: "Complete necessary paperwork and agreements"
        },
        {
          step: "3",
          title: "Onboarding",
          description: "Vehicle gets listed on our platform"
        },
        {
          step: "4",
          title: "Start Earning",
          description: "Receive 70% of revenue from each booking"
        }
      ],
      faqs: [
        {
          question: "Which vehicles can I list?",
          answer: "We accept bikes and cars that are less than 5 years old, in good condition, and have valid documentation."
        },
        {
          question: "Who handles maintenance?",
          answer: "We take care of all maintenance, repairs, and insurance claims. Maintenance costs are covered from revenue share."
        },
        {
          question: "What about insurance?",
          answer: "We provide comprehensive insurance coverage for all listed vehicles at no additional cost to you."
        },
        {
          question: "Can I use my vehicle when needed?",
          answer: "Yes! You can block dates for personal use through our Partner App with advance notice."
        }
      ]
    }
  ];

  const successStories = [
    {
      name: "Hirock Pegu",
      city: "Jorhat",
      vehicle: "Honda Activa",
      earnings: "₹15,000/month",
      duration: "8 months",
      type: "list"
    },
    {
      name: "Priya Sharma",
      city: "Sivsagar",
      vehicle: "Maruti Swift",
      earnings: "₹35,000/month",
      duration: "1 year",
      type: "invest"
    },
    {
      name: "Sameer Saikia",
      city: "Tinsukia",
      vehicle: "Royal Enfield Classic 350",
      earnings: "₹32,000/month",
      duration: "6 months",
      type: "list"
    },
    {
      name: "Sneha Borah",
      city: "Guwahati",
      investment: "₹800,000",
      earnings: "₹58,000/month",
      duration: "2 years",
      type: "invest"
    }
  ];

  const stats = [
    { number: "500+", label: "Active Partners" },
    { number: "₹70Lakhs+", label: "Annual Payouts" },
    { number: "4.9/5", label: "Partner Satisfaction" },
    { number: "24-48h", label: "Payout Processing" }
  ];

  return (
    <div className="relative min-h-screen">
      {/* Background Image */}
      <div className="fixed inset-0 z-0 overflow-hidden pointer-events-none">
        <div 
          className="absolute left-0 top-0 bottom-0 w-1/2 bg-cover bg-center bg-no-repeat opacity-20"
          style={{
            backgroundImage: `url(${allRideRentalImage})`,
            backgroundPosition: "left center",
            filter: "invert(100%)"
          }}
        ></div>
      </div>
      
      <div className="relative z-10 max-w-7xl mx-auto px-4 py-16">
        {/* Hero Section */}
        <div className="text-center mb-16">
          <h1 className="text-4xl md:text-5xl font-bold text-slate-800 mb-6">
            Partner with <span className="text-gold-500">All Ride Rental</span>
          </h1>
          <p className="text-xl text-slate-600 max-w-3xl mx-auto mb-8 leading-relaxed">
            Turn your vehicles into passive income or invest in our fleet. Earn 70% revenue share with our proven partnership models.
          </p>
          
          {/* Stats */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 max-w-4xl mx-auto mb-12">
            {stats.map((stat, index) => (
              <div key={index} className="bg-white/90 backdrop-blur-sm rounded-xl p-6 border border-blue-200 shadow-lg">
                <div className="text-2xl md:text-3xl font-bold text-gold-500 mb-2">{stat.number}</div>
                <div className="text-slate-700 text-sm">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Partnership Models Tabs */}
        <div className="mb-16">
          <div className="flex flex-col sm:flex-row gap-4 justify-center mb-8">
            {partnershipModels.map((model) => (
              <button
                key={model.id}
                onClick={() => setActiveTab(model.id)}
                className={`px-8 py-4 rounded-xl font-semibold text-lg transition-all duration-300 flex items-center justify-center gap-3 ${
                  activeTab === model.id
                    ? `bg-gradient-to-r ${model.color} text-white shadow-xl scale-105`
                    : "bg-white text-slate-700 border-2 border-gray-200 hover:border-gold-300"
                }`}
              >
                <span className="text-2xl">{model.icon}</span>
                {model.title}
              </button>
            ))}
          </div>

          {/* Active Model Content */}
          {partnershipModels
            .filter(model => model.id === activeTab)
            .map((model) => (
              <div key={model.id} className="bg-white/95 backdrop-blur-lg rounded-2xl p-8 border border-blue-200 shadow-xl">
                <div className="text-center mb-10">
                  <h2 className="text-3xl font-bold text-slate-800 mb-3">{model.title}</h2>
                  <p className="text-lg text-slate-600">{model.subtitle}</p>
                </div>

                <div className="grid md:grid-cols-2 gap-8 mb-12">
                  {/* Features */}
                  <div>
                    <h3 className="text-xl font-semibold text-slate-800 mb-6 pb-3 border-b border-gray-200">Key Benefits</h3>
                    <ul className="space-y-4">
                      {model.features.map((feature, index) => (
                        <li key={index} className="flex items-start">
                          <span className="text-green-500 mr-3 text-xl">✓</span>
                          <span className="text-slate-700">{feature}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  {/* How It Works */}
                  <div>
                    <h3 className="text-xl font-semibold text-slate-800 mb-6 pb-3 border-b border-gray-200">How It Works</h3>
                    <div className="space-y-6">
                      {model.howItWorks.map((step) => (
                        <div key={step.step} className="flex items-start">
                          <div className="flex-shrink-0 w-10 h-10 bg-gold-500 rounded-full flex items-center justify-center text-white font-bold mr-4">
                            {step.step}
                          </div>
                          <div>
                            <h4 className="font-semibold text-slate-800 mb-1">{step.title}</h4>
                            <p className="text-slate-600 text-sm">{step.description}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>

                {/* FAQs */}
                <div className="mb-12">
                  <h3 className="text-xl font-semibold text-slate-800 mb-6 pb-3 border-b border-gray-200">Frequently Asked Questions</h3>
                  <div className="grid md:grid-cols-2 gap-6">
                    {model.faqs.map((faq, index) => (
                      <div key={index} className="bg-blue-50 rounded-xl p-5">
                        <h4 className="font-semibold text-slate-800 mb-2">{faq.question}</h4>
                        <p className="text-slate-600 text-sm">{faq.answer}</p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            ))}
        </div>

        {/* Success Stories */}
        <div className="mb-16">
          <h2 className="text-3xl font-bold text-slate-800 text-center mb-10">Success Stories</h2>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {successStories.map((story, index) => (
              <div key={index} className="bg-white/95 backdrop-blur-lg rounded-2xl p-6 border border-blue-200 shadow-lg hover:shadow-xl transition-all duration-300 hover:translate-y-[-4px]">
                <div className="flex items-center mb-4">
                  <div className="w-12 h-12 bg-gradient-to-r from-gold-400 to-gold-600 rounded-full flex items-center justify-center text-white font-bold text-lg">
                    {story.name.charAt(0)}
                  </div>
                  <div className="ml-4">
                    <h4 className="font-semibold text-slate-800">{story.name}</h4>
                    <p className="text-slate-600 text-sm">{story.city}</p>
                  </div>
                </div>
                <div className="space-y-3">
                  <div className="flex justify-between">
                    <span className="text-slate-600 text-sm">Type:</span>
                    <span className="font-semibold text-gold-600 text-sm">
                      {story.type === 'invest' ? 'Investment' : 'Listing'}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-600 text-sm">{story.type === 'invest' ? 'Investment:' : 'Vehicle:'}</span>
                    <span className="font-semibold text-slate-800 text-sm">
                      {story.vehicle || story.investment}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-600 text-sm">Earnings:</span>
                    <span className="font-semibold text-green-600 text-sm">{story.earnings}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-600 text-sm">Duration:</span>
                    <span className="font-semibold text-slate-800 text-sm">{story.duration}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Partner App Feature */}
        <div className="bg-gradient-to-r from-blue-50 to-cyan-50 rounded-2xl p-8 md:p-12 border border-blue-300 shadow-lg mb-16">
          <div className="flex flex-col md:flex-row items-center">
            <div className="md:w-1/2 mb-8 md:mb-0 md:pr-12">
              <h2 className="text-3xl font-bold text-slate-800 mb-4">All Ride Partner App</h2>
              <p className="text-slate-700 mb-6">
                Track your earnings, manage vehicles, and monitor performance in real-time through our exclusive Partner App.
              </p>
              <ul className="space-y-3 mb-8">
                <li className="flex items-center">
                  <span className="text-blue-500 mr-3">📊</span>
                  <span>Real-time earnings dashboard</span>
                </li>
                <li className="flex items-center">
                  <span className="text-blue-500 mr-3">📱</span>
                  <span>Booking notifications and updates</span>
                </li>
                <li className="flex items-center">
                  <span className="text-blue-500 mr-3">💰</span>
                  <span>Monthly payout statements</span>
                </li>
                <li className="flex items-center">
                  <span className="text-blue-500 mr-3">🔧</span>
                  <span>Maintenance request tracking</span>
                </li>
              </ul>
              <button className="bg-gold-500 hover:bg-gold-600 text-white px-6 py-3 rounded-lg font-semibold transition-all duration-300 hover:scale-105 shadow-lg">
                Download Partner App
              </button>
            </div>
            <div className="md:w-1/2">
              <div className="bg-white rounded-2xl p-6 shadow-xl">
                <img 
                  src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80" 
                  alt="Partner App Dashboard"
                  className="rounded-xl w-full h-auto"
                />
              </div>
            </div>
          </div>
        </div>

        {/* Contact Form */}
        <div className="bg-white/95 backdrop-blur-lg rounded-2xl p-8 border border-blue-200 shadow-xl">
          <div className="text-center mb-10">
            <h2 className="text-3xl font-bold text-slate-800 mb-3">Start Your Partnership Journey</h2>
            <p className="text-slate-600">Fill out the form below and our partnership team will contact you within 24 hours</p>
          </div>

          <form onSubmit={handleSubmit} className="max-w-3xl mx-auto">
            <div className="grid md:grid-cols-2 gap-6 mb-6">
              <div>
                <label className="block text-slate-700 text-sm font-medium mb-2">Full Name *</label>
                <input
                  type="text"
                  name="name"
                  value={formData.name}
                  onChange={handleInputChange}
                  required
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-gold-500 focus:border-gold-500 transition-all"
                  placeholder="Enter your full name"
                />
              </div>
              <div>
                <label className="block text-slate-700 text-sm font-medium mb-2">Phone Number *</label>
                <input
                  type="tel"
                  name="phone"
                  value={formData.phone}
                  onChange={handleInputChange}
                  required
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-gold-500 focus:border-gold-500 transition-all"
                  placeholder="Enter your phone number"
                />
              </div>
            </div>

            <div className="grid md:grid-cols-2 gap-6 mb-6">
              <div>
                <label className="block text-slate-700 text-sm font-medium mb-2">Email Address *</label>
                <input
                  type="email"
                  name="email"
                  value={formData.email}
                  onChange={handleInputChange}
                  required
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-gold-500 focus:border-gold-500 transition-all"
                  placeholder="Enter your email"
                />
              </div>
              <div>
                <label className="block text-slate-700 text-sm font-medium mb-2">City *</label>
                <input
                  type="text"
                  name="city"
                  value={formData.city}
                  onChange={handleInputChange}
                  required
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-gold-500 focus:border-gold-500 transition-all"
                  placeholder="Enter your city"
                />
              </div>
            </div>

            <div className="mb-6">
              <label className="block text-slate-700 text-sm font-medium mb-3">Partnership Type *</label>
              <div className="flex flex-col sm:flex-row gap-4">
                <label className={`flex-1 cursor-pointer border-2 rounded-xl p-4 transition-all ${formData.partnershipType === 'invest' ? 'border-gold-500 bg-gold-50' : 'border-gray-300 hover:border-gold-300'}`}>
                  <input
                    type="radio"
                    name="partnershipType"
                    value="invest"
                    checked={formData.partnershipType === 'invest'}
                    onChange={handleInputChange}
                    className="mr-3"
                  />
                  <div>
                    <div className="font-semibold text-slate-800">Invest in New Vehicles</div>
                    <div className="text-slate-600 text-sm">Buy through us, earn 70% revenue share</div>
                  </div>
                </label>
                <label className={`flex-1 cursor-pointer border-2 rounded-xl p-4 transition-all ${formData.partnershipType === 'list' ? 'border-gold-500 bg-gold-50' : 'border-gray-300 hover:border-gold-300'}`}>
                  <input
                    type="radio"
                    name="partnershipType"
                    value="list"
                    checked={formData.partnershipType === 'list'}
                    onChange={handleInputChange}
                    className="mr-3"
                  />
                  <div>
                    <div className="font-semibold text-slate-800">List Existing Vehicle</div>
                    <div className="text-slate-600 text-sm">List your vehicle, earn 70% revenue share</div>
                  </div>
                </label>
              </div>
            </div>

            <div className="grid md:grid-cols-2 gap-6 mb-6">
              <div>
                <label className="block text-slate-700 text-sm font-medium mb-2">Vehicle Type *</label>
                <select
                  name="vehicleType"
                  value={formData.vehicleType}
                  onChange={handleInputChange}
                  required
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-gold-500 focus:border-gold-500"
                >
                  <option value="">Select vehicle type</option>
                  <option value="bike">Bike / Scooter</option>
                  <option value="car">Car / SUV</option>
                  <option value="luxury">Luxury Vehicle</option>
                </select>
              </div>
              <div>
                <label className="block text-slate-700 text-sm font-medium mb-2">
                  {formData.partnershipType === 'invest' ? 'Investment Amount *' : 'Number of Vehicles *'}
                </label>
                {formData.partnershipType === 'invest' ? (
                  <select
                    name="investmentAmount"
                    value={formData.investmentAmount}
                    onChange={handleInputChange}
                    required
                    className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-gold-500 focus:border-gold-500"
                  >
                    <option value="">Select investment range</option>
                    <option value="1-2">₹50,000 - ₹1,00,000</option>
                    <option value="2-5">₹1,00,000 - ₹5,00,000</option>
                    <option value="5-10">₹5,00,000 - ₹10,00,000</option>
                    <option value="10+">₹10,00,000+</option>
                  </select>
                ) : (
                  <select
                    name="vehicleCount"
                    value={formData.vehicleCount}
                    onChange={handleInputChange}
                    required
                    className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-gold-500 focus:border-gold-500"
                  >
                    <option value="1">1 Vehicle</option>
                    <option value="2">2 Vehicles</option>
                    <option value="3">3 Vehicles</option>
                    <option value="4+">4+ Vehicles</option>
                  </select>
                )}
              </div>
            </div>

            <div className="mb-6">
              <label className="block text-slate-700 text-sm font-medium mb-2">Additional Message</label>
              <textarea
                name="message"
                value={formData.message}
                onChange={handleInputChange}
                rows="4"
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-gold-500 focus:border-gold-500 transition-all"
                placeholder="Tell us about your requirements or ask any questions..."
              ></textarea>
            </div>

            <div className="text-center">
              <button
                type="submit"
                className="bg-gradient-to-r from-gold-500 to-gold-600 hover:from-gold-600 hover:to-gold-700 text-white px-12 py-4 rounded-xl font-semibold text-lg transition-all duration-300 hover:scale-105 shadow-lg"
              >
                Submit Partnership Request
              </button>
              <p className="text-slate-600 text-sm mt-4">
                By submitting, you agree to our Terms of Service and Privacy Policy
              </p>
            </div>
          </form>
        </div>

        {/* Bottom CTA */}
        <div className="text-center mt-16">
          <div className="inline-flex flex-col sm:flex-row items-center bg-gradient-to-r from-gold-100 to-gold-200 rounded-2xl px-8 py-6 border border-gold-300 shadow-lg">
            <div className="mb-4 sm:mb-0 sm:mr-8">
              <h3 className="text-2xl font-bold text-slate-800 mb-2">Still have questions?</h3>
              <p className="text-slate-700">Our partnership team is here to help</p>
            </div>
            <div className="flex gap-4">
              <button className="bg-gold-500 hover:bg-gold-600 text-white px-6 py-3 rounded-lg font-semibold transition-all duration-300 hover:scale-105 shadow-lg">
                📞 Call Now
              </button>
              <button className="bg-white hover:bg-blue-50 text-slate-800 px-6 py-3 rounded-lg font-semibold transition-all duration-300 hover:scale-105 border border-blue-300">
                💬 WhatsApp
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PartnerPage;